export const TAG_TYPES = [
  {
    label: "フロント",
    data: [
      "HTML",
      "CSS",
      "JavaScript",
      "jQuery",
      "React",
      "Angular",
      "Vue",
      "TypeScript",
      "CoffeeScript",
    ],
  },
  {
    label: "バックエンド",
    data: [
      "C",
      "C+",
      "C#",
      "Java",
      "Ruby",
      "PHP",
      "Phyton",
      "Objective-C",
      "Perl",
    ],
  },
  {
    label: "その他",
    data: [
      "Node.js",
      "Swift",
      "kotolin",
      "Bootstrap",
      "JUnit",
      "MySQL",
      "PostgreSQL",
      "Oracle",
      "SQLite",
      "MongoDB",
      "SQL",
      "Git",
      "GitHub",
      "GitLab",
      "Docker",
      "AWS",
      "Heroku",
      "Linux",
      "Bash",
      "CentOS",
      "shell",
      "Redmine",
      "Postman",
      "Atom",
      "ssh",
    ],
  },
];
export const ENGINEER_TYPES = ["FR", "WEB", "ML", "CL", "QA"];
