import { SkillTags } from "./Types";

export const SKILL: SkillTags = [
  {
    label: "フロント",
    tags: [
      { id: 1, skill: "HTML", image: null },
      { id: 2, skill: "CSS", image: null },
      { id: 3, skill: "JavaScript", image: null },
      { id: 4, skill: "jQuery", image: null },
      { id: 5, skill: "React", image: null },
      { id: 6, skill: "Angular", image: null },
      { id: 7, skill: "Vue", image: null },
      { id: 8, skill: "TypeScript", image: null },
      { id: 9, skill: "CoffeeScript", image: null },
    ],
  },
  {
    label: "バックエンド・その他",
    tags: [
      { id: 10, skill: "C", image: null },
      { id: 11, skill: "C+", image: null },
      { id: 12, skill: "C#", image: null },
      { id: 13, skill: "Java", image: null },
      { id: 14, skill: "Ruby", image: null },
      { id: 15, skill: "Phyton", image: null },
      { id: 16, skill: "Objective-C", image: null },
      { id: 17, skill: "Perl", image: null },
      { id: 18, skill: "Node.js", image: null },
      { id: 19, skill: "Swift", image: null },
      { id: 20, skill: "kotlin", image: null },
      { id: 21, skill: "AWS", image: null },
      { id: 22, skill: "Unity", image: null },
      { id: 23, skill: "Linux", image: null },
      { id: 24, skill: "Ubuntu", image: null },
      { id: 25, skill: "WordPress", image: null },
      { id: 26, skill: "PostgreSQL", image: null },
      { id: 27, skill: "Flutter", image: null },
      { id: 28, skill: "Excel", image: null },
      { id: 29, skill: "Xcode", image: null },
      { id: 30, skill: "Windows", image: null },
      { id: 31, skill: "Laravel", image: null },
      { id: 32, skill: "PHP", image: null },
      { id: 33, skill: "Mac", image: null },
      { id: 34, skill: "iOS", image: null },
      { id: 35, skill: "MySQL", image: null },
      { id: 36, skill: "MariaDB", image: null },
      { id: 37, skill: "MongoDB", image: null },
      { id: 38, skill: "GitHub", image: null },
      { id: 39, skill: "EC2", image: null },
      { id: 40, skill: "CentOS", image: null },
      { id: 41, skill: "Docker", image: null },
      { id: 42, skill: "Heroku", image: null },
      { id: 43, skill: "TensorFlow", image: null },
      { id: 44, skill: "GCP", image: null },
      { id: 45, skill: "pandas", image: null },
      { id: 46, skill: "JSON", image: null },
      { id: 47, skill: "nuxt.js", image: null },
      { id: 48, skill: "next.js", image: null },
      { id: 49, skill: "numpy", image: null },
      { id: 50, skill: "Dart", image: null },
      { id: 51, skill: "eclipse", image: null },
      { id: 52, skill: "Flask", image: null },
      { id: 53, skill: "Django", image: null },
      { id: 54, skill: "Bootstrap", image: null },
      { id: 55, skill: "VScode", image: null },
      { id: 56, skill: "Firebase", image: null },
      { id: 57, skill: "Tailwind CSS", image: null },
      { id: 58, skill: "S3", image: null },
      { id: 59, skill: "AngularJS", image: null },
      { id: 60, skill: "API", image: null },
    ],
  },
];
export const ENGINEER = ["FR", "WEB", "ML", "CL", "QA"];
// export const SKILL: SkillTags = [
//   {
//     label: "職種",
//     tags: [
//       { id: 1, skill: "FR", image: null },
//       { id: 2, skill: "Web", image: null },
//       { id: 3, skill: "CL", image: null },
//       { id: 4, skill: "ML", image: null },
//       { id: 5, skill: "QA", image: null },
//     ],
//   },
//   {
//     label: "技術",
//     tags: [
//       { id: 6, skill: "TypeScript", image: null },
//       { id: 7, skill: "Java", image: null },
//       { id: 8, skill: "AWS", image: null },
//       { id: 9, skill: "Docker", image: null },
//       { id: 10, skill: "Next.js", image: null },
//       { id: 11, skill: "React", image: null },
//       { id: 12, skill: "Nuxt.js", image: null },
//       { id: 13, skill: "Vue", image: null },
//       { id: 14, skill: "JavaScript", image: null },
//       { id: 15, skill: "JEST", image: null },
//       { id: 16, skill: "CSS", image: null },
//       { id: 17, skill: "Nest", image: null },
//       { id: 18, skill: "GraphQL", image: null },
//       { id: 19, skill: "MongoDB", image: null },
//     ],
//   },
// ];
// export const ENGINEER = ["FR", "WEB", "ML", "CL", "QA"];
